HIGHLY_VAR_GENES_PATH: "/home/jholz/fraenkel_rotation/mcBERT-cellprofiler/generated/feat.csv"
H5AD_FILES: "/home/jholz/fraenkel_rotation/mcBERT-cellprofiler/h5ad_files/standardized_originalfeat/DMSO/*.h5ad"

modality: 'cellprofiler-features'
device: 'cuda'

train:
  log_dir: '/home/jholz/fraenkel_rotation/mcBERT-cellprofiler/0utputs/pretrain_DMSO_only/logs'          # ADAPT LOG DIRECTORY
  checkpoints_dir: '/home/jholz/fraenkel_rotation/mcBERT-cellprofiler/0utputs/pretrain_DMSO_only/checkpoints'  # ADAPT CHECKPOINTS DIRECTORY
  batch_size: 16
  eval_batch_size: 16
  num_epochs: 50
  save_ckpt_freq: 50
  oversampling: true
val:
  oversampling: false

criterion:
  loss_beta: 4

optimizer:
  lr: 1e-5
  weight_decay: 0.01

dataset:
  mlm_probability: 0.15

model:
  name: 'D2V_pretraining_cellprofiler'
  vocab_size: 581               # 579 features + 1 CLS + 1 MSK
  average_top_k_layers: 6 
  embed_dim: 288
  hidden_size: 288
  num_hidden_layers: 12
  num_attention_heads: 12
  normalize_targets: true
  ema_decay: 0.999
  ema_end_decay: 0.9999
  ema_anneal_end_step: 300000